### PR TITLE
july 2015 meetup details

### PR DESCRIPTION
**Pull request by lawnsea**
FIXME:
- [x] sponsor
- [x] get @jennschiffer and @ajpiano to approve their bios

### CODE REVIEW

**Comment by jennschiffer** [comment]
:boat: it

**Comment by aaronj1335** [comment]
hmm... running this locally i'm seeing a bunch of markdown links not rendering...

**Comment by aaronj1335** [comment]
oh lol can't use markup in the html. i'll clean that up with the sponsor info.

**Comment by lawnsea** [comment]
lol markdown for what!

**Comment by miketaylr** [comment]
> oh lol can't use markup in the html

We need to have a talk @aaronj1335

**Comment by aaronj1335** [comment]
a wild @miketaylr spotting!

**Comment by aaronj1335** [comment]
oh and before someone makes the yo dawg joke, just don't.

**Comment by miketaylr** [comment]
how about oy dawg jokes

**Comment by aaronj1335** [comment]
skeptical-at-first

**Comment by lawnsea** [comment]
:shipit:

**Comment by jennschiffer** [comment]
i don't know who any of you are

**Comment by miketaylr** [comment]
maybe this will jog your memory

**Comment by jennschiffer** [comment]
oh you know what, something came up and i don't think i'll be able to make it on the 21st

**Pull request closed without merging**
