### PR TITLE
october 2015 meetup blog post

### PR DESCRIPTION
**Pull request by lawnsea**
#wubwubwub

- [x] needs sponsor details

### CODE REVIEW

**Comment by lawnsea** [comment]
@joemccann @aaronj1335

**Comment by lawnsea** [comment]
@aaronj1335 we need the sponsor details before we can land this

**Comment by fivetanley** [comment]
maybe we can get buy2hams to sponsor https://twitter.com/buy_2_hams

**Comment by aaronj1335** [comment]
what... what's the catch tho??

**Comment by aaronj1335** [comment]
lawnsea/austinjavascript.github.io/pull/3

**Comment by aaronj1335** [comment]
this looks good to me otherwise too

**Comment by lawnsea** [comment]
Closed by 20b82ff280eed51c07504201a9b2ace490ff6cbe

**Pull request closed without merging**
