### PR TITLE
don't click that link i dare you

### PR DESCRIPTION
**Pull request by aaronj1335**
pertains to #31 

@savetheclocktower let us know if you'd got any less-dated references you'd like to see in this one.

### CODE REVIEW

**Comment by savetheclocktower** [comment]
I haven't done dupontCAPS in years. Maybe point out that I spend my day job `git blame`-ing lines that turn out to have been written by @pifantastic and @SlexAxton. Otherwise this is just fine.

Also, I just realized I haven't changed my Twitter profile description in like eight years, so I fixed that.

**Comment by aaronj1335** [comment]
updated!

**Comment by savetheclocktower** [comment]
👍

**Comment by lawnsea** [comment]
👍 

i shoulda written more code for you to `git blame` i guess

**Comment by SlexAxton** [comment]
Rude

**Comment by aaronj1335** [comment]
brb updating my linkedin career goals to include getting my code git blame'd by @savetheclocktower

**Pull request closed without merging**
